Uninstaller changed to use MS-DOS partition and "BOOT" label. This should be later updated to work with both GPT and MS-DOS-compatible partition tables, but only when other routines will have consistent support of both.

diff --git a/machine/im_n29xx_t40n/rootconf/lib/onie/uninstall-arch b/machine/im_n29xx_t40n/rootconf/lib/onie/uninstall-arch
--- a/machine/im_n29xx_t40n/rootconf/lib/onie/uninstall-arch
+++ b/machine/im_n29xx_t40n/rootconf/lib/onie/uninstall-arch
@@ -2,13 +2,13 @@
 
 # Erase a block device partition
 # Step 1 -- Overwrite the partition with random data
-# Step 2 -- Remove the partition from the GPT partition table
+# Step 2 -- Remove the partition from the MS-DOS-compatible partition table
 erase_part()
 {
     blk_dev="$1"
     part="$2"
 
-    device="${blk_dev}$part"
+    device="${blk_dev}${part}"
     dev_sz=$(blockdev --getsize64 /dev/$device)
     cur_sz=0
     count=0
@@ -32,8 +32,8 @@ erase_part()
 
     if [ "$onie_testing" != "y" ] ; then
         printf "${log_pre}Deleting partition $part from /dev/$blk_dev\n"
-        sgdisk -d $part /dev/$blk_dev > /dev/null 2>&1 || {
-            printf "${log_pre}Unable to remove partition $name, $part on /dev/$blk_dev\n"
+	parted -s /dev/$blk_dev rm $part 2>&1 || {
+            printf "${log_pre}Unable to remove partition $part on /dev/$blk_dev\n"
             return 1
         }
     fi
@@ -44,7 +44,7 @@ uninstall_system()
 {
 
     # Clean up block device that contains ONIE
-    blk_dev=$(blkid | grep ONIE-BOOT | awk '{print $1}' | sed -e 's/[0-9]://' | head -n 1 | sed -e 's#/dev/##')
+    blk_dev=$(blkid | grep BOOT | awk '{print $1}' | sed -e 's/[0-9]://' | head -n 1 | sed -e 's#/dev/##')
 
     [ -b "/dev/$blk_dev" ] || {
         echo "Error: Unable to determine block device of ONIE install"
@@ -54,11 +54,11 @@ uninstall_system()
     # Wipe out and delete all partitions, except for the ONIE and GRUB
     # partitions.
     ls -d /sys/block/$blk_dev/${blk_dev}* | sed -e "s/^.*$blk_dev//" | while read part ; do
-        name="$(sgdisk -i $part /dev/$blk_dev | grep 'Partition name:')"
+        name="$(blkid "/dev/${blk_dev}${part}" | tr ' ' '\n'|egrep ^LABEL=| cut -d'"' -f2)"
         name=${name#*"'"}
         name=${name%"'"*}
         case "$name" in
-            GRUB-BOOT|ONIE-BOOT|ONIE-CONFIG)
+            GRUB-BOOT|ONIE-BOOT|ONIE-CONFIG|BOOT)
                 # echo "skipping ONIE part"
                 continue
                 ;;
